# Generated by Django 5.1.7 on 2025-05-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_notifications', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='subscription',
            field=models.TextField(),
        ),
    ]
